
spring.application.name=Milkao

spring.datasource.url=jdbc:mysql://localhost:3306/milkoa
spring.datasource.username=root
spring.datasource.password=Marine2311@

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true